---
- name: Deploy K3s Master
  hosts: master

  tasks:
  - name: install k3s master
    shell: >
      curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -s - server --bind-address 192.168.1.110 --advertise-address 192.168.1.110

  - name:  install kubernetes dashboard
    shell: 
      kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.2.0/aio/deploy/recommended.yaml

  - name:  install kubernetes dashboard
    shell: > 
      kubectl apply -f dashboard.admin-user.yml

  - name:  install kubernetes dashboard
    shell: > 
      kubectl apply -f dashboard.admin-user-role.yml

  - name: get node token
    slurp:
      src: /var/lib/rancher/k3s/server/node-token
    register: token

  - name: add token holder
    add_host:
      name: "K3S_TOKEN_HOLDER"
      token: "{{ token.content | b64decode }}"

- name: Deploy k3s workers
  hosts: worker

  tasks:
  
  - name: install k3s workers
    shell: >
      curl -sfL https://get.k3s.io | K3S_URL='https://192.168.0.110:6443' K3S_TOKEN="{{ hostvars['K3S_TOKEN_HOLDER']['token'] }}" sh -
